steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/rational-autumn-494910-p2/job-agent/agents:latest'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/rational-autumn-494910-p2/job-agent/agents:latest'
